package marv.allib.ksp

import com.google.auto.service.AutoService
import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ksp.*
import marv.allib.contracts.AlibService
import java.io.OutputStream

class AlibKspProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("marv.allib.contracts.AlibService")
        val validSymbols = mutableListOf<KSAnnotated>()
        val visitor = ServiceCollectorVisitor()

        symbols.forEach { symbol ->
            symbol.accept(visitor, Unit)
        }

        val services = visitor.getServices()
        if (services.isNotEmpty()) {
            generateServiceLoader(services)
        }

        return emptyList()
    }

    private fun generateServiceLoader(services: List<ServiceInfo>) {
        val fileSpec = FileSpec.builder("marv.allib.ksp.generated", "AlibServiceLoader")
            .addFileComment("Generated by allib-ksp")
            .addFunction(
                FunSpec.builder("loadServices")
                    .addStatement("val services = mutableListOf<%T>()", ClassName("marv.allib.contracts", "IAlibService"))
                    .apply {
                        services.forEach { service ->
                            addStatement("services.add(%T())", ClassName.bestGuess(service.className))
                        }
                    }
                    .addStatement("return services")
                    .build()
            )
            .build()

        val outputStream: OutputStream = codeGenerator.createNewFile(
            Dependencies.ALL_FILES,
            "marv.allib.ksp.generated",
            "AlibServiceLoader"
        )
        outputStream.write(fileSpec.toString().toByteArray())
        outputStream.close()
    }

    private class ServiceCollectorVisitor : KSVisitorVoid() {
        private val services = mutableListOf<ServiceInfo>()

        override fun visitClassDeclaration(classDeclaration: KSClassDeclaration, data: Unit) {
            val annotation = classDeclaration.annotations
                .find { it.shortName.asString() == "AlibService" }
                ?: return

            val className = classDeclaration.qualifiedName?.asString() ?: return
            val id = getAnnotationArgument<String>(annotation, "id") ?: className
            val version = getAnnotationArgument<String>(annotation, "version") ?: "1.0.0"
            val dependencies = getAnnotationArgument<List<String>>(annotation, "dependencies") ?: emptyList()

            services.add(ServiceInfo(className, id, version, dependencies))
        }

        private fun <T> getAnnotationArgument(annotation: KSAnnotation, name: String): T? {
            val arg = annotation.arguments.find { it.name?.asString() == name } ?: return null
            return arg.value as? T
        }

        fun getServices(): List<ServiceInfo> = services.toList()
    }

    data class ServiceInfo(
        val className: String,
        val id: String,
        val version: String,
        val dependencies: List<String>
    )
}

class AlibKspProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return AlibKspProcessor(
            environment.codeGenerator,
            environment.logger,
            environment.options
        )
    }
}
